chore(githooks): refactor for clarity

diff --git a/scripts/.git-hooks/post-checkout b/scripts/.git-hooks/post-checkout
--- a/scripts/.git-hooks/post-checkout
+++ b/scripts/.git-hooks/post-checkout
@@ -35,13 +35,12 @@ config_git_project_gitconfig
 
 if [ "$GIT_LFS_ENABLED" == "true" ]; then
     # [1] handle Git LFS (handles binary files because per line changes are not desired)
-    if command -v git-lfs >/dev/null 2>&1; then
-        explicit_run_cmd "git lfs post-checkout $*"
-    else
+    if ! command -v git-lfs >/dev/null 2>&1; then
         error "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path."
         error "Please install to continue to use this repository!\n"
         exit 2
     fi
+    explicit_run_cmd "git lfs post-checkout $*"
 fi
 
 # [2] Verifying git's GPG configuration
@@ -67,23 +66,14 @@ if [ "$CKOUT_TYPE_FLAG" = "1" ] && [ "$IS_CLONING" = "false" ]; then
         bkgd_pids="$bkgd_pids $!"
     fi
 
-    if [ -n "$bkgd_pids" ]; then
-        # wait for deps manager processes to complete
-        overall_exitcode=0
-        for pid in $bkgd_pids; do
-            if ! wait "$pid"; then
-                overall_exitcode=1
-            fi
-        done
-
-        if ! [ $overall_exitcode -eq 0 ]; then
-            error "dependency environment...synchronization failed!"
-            env_cleanup
-            exit 1
-        fi
-
-        log "dependency environment...synchronized!"
+    # wait for deps manager processes to complete
+    if ! wait_for_all_children "$bkgd_pids"; then
+        error "dependency environment...synchronization failed!"
+        env_cleanup
+        exit 1
     fi
+
+    log "dependency environment...synchronized!"
 fi
 
 # env cleanup (vars, functions, utils)
diff --git a/scripts/.git-hooks/post-rewrite b/scripts/.git-hooks/post-rewrite
--- a/scripts/.git-hooks/post-rewrite
+++ b/scripts/.git-hooks/post-rewrite
@@ -45,23 +45,13 @@ if contains_pyprojecttoml_file "$modified_files_in_rebase"; then
     bkgd_pids="$bkgd_pids $!"
 fi
 
-if [ -n "$bkgd_pids" ]; then
-    # wait for deps manager processes to complete
-    overall_exitcode=0
-    for pid in $bkgd_pids; do
-        if ! wait "$pid"; then
-            overall_exitcode=1
-        fi
-    done
-
-    if ! [ $overall_exitcode -eq 0 ]; then
-        error "dependency environment...synchronization failed!"
-        env_cleanup
-        exit "$overall_exitcode"
-    fi
-
-    log "dependency environment...synchronized!"
+if ! wait_for_all_children "$bkgd_pids"; then
+    error "dependency environment...synchronization failed!"
+    env_cleanup
+    exit 1
 fi
+
+log "dependency environment...synchronized!"
 
 # env cleanup (vars, functions, utils)
 env_cleanup
diff --git a/scripts/.git-hooks/prepare-commit-msg b/scripts/.git-hooks/prepare-commit-msg
--- a/scripts/.git-hooks/prepare-commit-msg
+++ b/scripts/.git-hooks/prepare-commit-msg
@@ -28,12 +28,20 @@ if [ "$COMMIT_MSG_SOURCE" = "merge" ] ||
     exit 0
 fi
 
+COMMITIZEN_EXE="$VIRTUAL_ENV/bin/cz"
+
+if ! [ -e "$COMMITIZEN_EXE" ]; then
+    error "ERROR: Unable to find commitizen cli"
+    error "WARNING: proceeding at risk."
+    exit 0
+fi
+
 # Default
 # run as dry run to write to file only and exit with success (use as git hook)
 CZ_OPTIONS="--write-message-to-file $COMMIT_MSG_FILE --dry-run"
 
 # if [ "$CZ_RETRY" = "true" ]; then   # Currently not supported by py-commitizen due to no true backup
-#     CZ_OPTIONS="--retry"
+#     CZ_OPTIONS="$CZ_OPTIONS --retry"
 # elif ! exec </dev/tty; then
 if ! exec </dev/tty; then
     error "Unable to activate <stdin> for interactive shell for commitizen cli"
@@ -43,15 +51,11 @@ if ! exec </dev/tty; then
     exit 0
 fi
 
-if [ -e "$VIRTUAL_ENV/bin/cz" ]; then
-    COMMITIZEN_CMD="$VIRTUAL_ENV/bin/cz cz commit $CZ_OPTIONS"
+COMMITIZEN_CMD="$COMMITIZEN_EXE commit $CZ_OPTIONS"
 
-    log "Starting commitizen cli for conventional commits..."
-    explicit_run_cmd "${COMMITIZEN_CMD} || (exit 0)"
-    unset -v COMMIT_MSG_FILE COMMITIZEN_CMD
-else
-    error "ERROR: Unable to find commitizen cli"
-fi
+log "Starting commitizen cli for conventional commits..."
+
+explicit_run_cmd "${COMMITIZEN_CMD} || (exit 0)"
 
 # env cleanup (vars, functions, utils)
 unset -v COMMIT_MSG_FILE COMMIT_MSG_SOURCE CZ_OPTIONS
